# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Josh/432L-1/432L-1.cache/wt [current_project]
set_property parent.project_path C:/Users/Josh/432L-1/432L-1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Josh/432L-1/432L-1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/top.v
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/clkdiv.v
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/top_dbg.v
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/system.v
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/mux_8.v
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/latch.v
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/new/i8255dbg.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/testbench/utils.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/dataregfile_rtl.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/432-1/prog_mem.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/biufsm_fsm.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/a_table.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/formatter_struct.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/432-1/system_main.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/biu_struct.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/cpu86instr.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/m_table.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/r_table.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/divider_rtl_ser.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/regshiftmux_regshift.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/432-1/pic.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/d_table.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/proc_rtl.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/datapath_struct.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/n_table.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/alu_rtl.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/ipregister_rtl.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/multiplier_rtl.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/cpu86pack.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/segregfile_rtl.vhd
  C:/Users/Josh/432L-1/432L-1.srcs/sources_1/imports/cpu86_rtl/cpu86_struct.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Josh/432L-1/432L-1.srcs/constrs_1/imports/DL/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Josh/432L-1/432L-1.srcs/constrs_1/imports/DL/Nexys-4-DDR-Master.xdc]


synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
